In [6]:
### Imports go here
import tweepy
from tweepy import OAuthHandler
import pandas as pd
import json
import time
import datetime
import pytz
from google.colab import files
import statistics


consumer_key = "Ja0rkGIQ7q0eiuDOTG1Ioiifz"
consumer_secret = "0MpwoLJEXaGno5WUpJELxRtvX1BnYhQlnwGIN20KGxgCwmNO1G"
access_token = "1643196206661914627-chgan8lehEqN8PdQXKGMUzCJyknqpj"
access_token_secret = "WDEm5dmsK0EYyFhWICiOjvUK6XTrHUDjgR2ASNeusCdLZ"

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True)

In [8]:
### Function to retrieve tweet from brand's stream
engagementrate = []
subs = [901831, 901758, 901672, 901641, 901693]
date = [datetime.datetime(2023,6,6,0,0,0,0,pytz.UTC),datetime.datetime(2023,6,7,0,0,0,0,pytz.UTC),datetime.datetime(2023,6,8,0,0,0,0,pytz.UTC)
        ,datetime.datetime(2023,6,9,0,0,0,0,pytz.UTC),datetime.datetime(2023,6,10,0,0,0,0,pytz.UTC)]
amplification = []
likespertweet = []
user_id = 'ROLEX'

def getTweet(x):
  tweets = []
  id = ''
  text = ''
  retweet = 0
  favorite = 0
  #user = api.get_user(screen_name=user_id)
  tweet = api.user_timeline(screen_name = user_id, count=100)
  tweetsondate = []
  i = 0

  for t in tweet:
                       # datetime.datetime.now()
      if t.created_at <= date[x]:
        if i < 30:
           # calculate engagement for each tweet             #user.followers_count
          engagement = (t.retweet_count + t.favorite_count) / subs[x] * 100
          # calculate amplification for each tweet
          amplification = (t.retweet_count) / subs[x] * 100
                                                                                             #user.followers_count
          tweetsondate.append([t.id, t.text, t.created_at, t.retweet_count, t.favorite_count, subs[x], engagement, amplification])
          i+=1
  columns= ["Tweet ID", "Tweet Text", "Tweet date", "Retweet Count", "Favorite Count", "Followers", "Engagement Rate", "Amplification Rate"]
  tweets_df = pd.DataFrame(tweetsondate, columns = columns)
  return tweets_df

for x in range(len(date)):
  engagement =getTweet(x)
  total = totalampli = 0
  for i in range(len(engagement)):
    total += engagement['Engagement Rate'][i]
    totalampli += engagement['Amplification Rate'][i]

  #calculate average likes per tweet
  likespertweet.append(statistics.mean(engagement['Favorite Count']))

  #calculation engagement rate
  engagementrate.append(total/len(engagement))

  #calculate amplication rate
  amplification.append(totalampli/len(engagement))

In [9]:
tweets = [758, 758, 758, 759, 760]
avgtweets = []
for x in range(len(date)):
  user = api.get_user(screen_name=user_id)
              # datetime.datetime.now()
  difference = date[x] - user.created_at
  #calculate average tweets per day
  avgtweets.append(tweets[x]/difference.days)

In [10]:
columns= ["Date", "Followers", "Audience Growth Rate", "Engagement Rate", "Amplification Rate", "Average Likes per tweet", "Average Tweets per day"]
tweets_df = pd.DataFrame(columns = columns)
tweets_df['Followers'] = subs
tweets_df['Engagement Rate'] = engagementrate
tweets_df['Date'] = date
tweets_df['Amplification Rate'] = amplification
tweets_df['Average Likes per tweet'] = likespertweet
tweets_df['Average Tweets per day'] = avgtweets

In [11]:
#calculation of audience growth rate
tweets_df['Audience Growth Rate'][0] = 0
for i in range(len(tweets_df)-1):
  tweets_df['Audience Growth Rate'][i+1] = (tweets_df['Followers'][i+1] - tweets_df['Followers'][i]) / tweets_df['Followers'][i]

<ipython-input-11-ec5894ed59b2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_df['Audience Growth Rate'][0] = 0
<ipython-input-11-ec5894ed59b2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_df['Audience Growth Rate'][i+1] = (tweets_df['Followers'][i+1] - tweets_df['Followers'][i]) / tweets_df['Followers'][i]

In [12]:
tweets_df

,Date,Followers,Audience Growth Rate,Engagement Rate,Amplification Rate,Average Likes per tweet,Average Tweets per day
0,2023-06-06 00:00:00+00:00,901831,0,0.036633,0.003840,295.733333,0.183669
1,2023-06-07 00:00:00+00:00,901758,-0.000081,0.036636,0.003841,295.733333,0.183624
2,2023-06-08 00:00:00+00:00,901672,-0.000095,0.036639,0.003841,295.733333,0.183580
3,2023-06-09 00:00:00+00:00,901641,-0.000034,0.035879,0.003756,289.633333,0.183777
4,2023-06-10 00:00:00+00:00,901693,0.000058,0.036180,0.003774,292.200000,0.183975

In [13]:
tweets_df.to_csv('rolex_twitter.csv', index = False)